-- The storeroom's page count in the database, brought up to three.
--
-- This is the SECOND half of the three-page storeroom, and it is not the half
-- that makes the third page appear. set_safebox_pages.py is: the game core
-- decides the size of the storeroom window itself, in CInputDB::SafeboxLoad,
-- and upstream's own line that read the size out of this table is commented
-- out one line above the line that does the work (input_db.cpp:1208 / :1209).
-- So a player would get three pages with this file and without it.
--
-- WHY IT IS HERE ANYWAY. player.safebox.size is still read by two things, and
-- both of them now disagree with what the core hands out:
--
--   * the db process, when it has an item_award waiting for an account. It
--     builds CGrid(5, MAX(1, size) * 9) (ClientManager.cpp:620) to find a free
--     cell for the award. At size 1 that grid is one page, so an award can only
--     ever be placed on page 1 and stops being delivered as soon as page 1 is
--     full -- even with pages 2 and 3 standing empty.
--   * quest scripts, through pc.get_safebox_size(), which returns
--     GetSafeboxSize() / SAFEBOX_PAGE_SIZE (questlua_game.cpp:59) seeded from
--     this column at login (char.cpp:5814, db.cpp:1247).
--
-- Leaving the column at 1 would not lose anything, but it would leave the
-- database saying one thing and the game doing another, and the next person to
-- read either of those two paths would have to work out which one was lying.
--
-- WHY THIS FILE IS SAFE TO RUN AGAIN. The panel's entrypoint applies every .sql
-- in its schema directory on EVERY start, not only when the database is first
-- created (panel/bin/entrypoint.sh, "2. Panel tables"), so this runs many times
-- over the life of an install -- and it is the one mechanism in this project
-- that reaches a database that already exists. The statement is therefore
-- written to converge rather than to change: WHERE size < 3 matches nothing on
-- the second run, and it can never shrink an account that some other means has
-- already given more. player.safebox.size is a TINYINT UNSIGNED, so 3 is well
-- inside it.
--
-- WHAT IT DOES NOT DO. It does not create safebox rows for accounts that have
-- none, and most accounts have none: a row is only ever inserted by
-- QUERY_SAFEBOX_CHANGE_SIZE (ClientManager.cpp:832), which nothing on this
-- server calls. Those accounts are not missing out -- the core does not consult
-- this column for the window size -- and inventing rows with an empty password
-- column for every account in a different database is a far larger thing to do
-- behind an operator's back than this file is worth.
--
-- No item is touched. This column is a page count and nothing indexes an item
-- by it; the cells an item sits in are decided by the grid the core builds, and
-- growing that grid only appends cells. See set_safebox_pages.py for that.
--
-- TO TAKE IT BACK OUT: turning the Custom Experience off stops this file being
-- staged, but it does not put a column back that is already changed -- undoing
-- an operator's data behind their back is not something a build switch should
-- do. Do it deliberately instead, and only together with reverting the core
-- patch:
--
--     UPDATE player.safebox SET size = 1 WHERE size = 3;

UPDATE safebox SET size = 3 WHERE size < 3;
