-- Musk Oil on the General Store Saleswoman's counter.
--
-- This is the one piece of the Custom Experience that lives in the database
-- rather than in a file, which is exactly why it went unnoticed for weeks: a
-- server that had it and a server that did not looked identical everywhere a
-- person would think to look, and the only way to tell them apart was to
-- compare two databases.
--
-- Shop 3 is the General Store Saleswoman (player.shop) and 30177 is Musk Oil,
-- which the quest new_quest_premium_lv4 asks the player to bring. Without this
-- row the quest cannot be finished at all on a server with no item shop, and
-- the rewritten quest text -- musk_oil_from_the_general_store.py, applied by
-- the same switch -- would be sending the player to an empty shelf. The two
-- belong together and are turned on together.
--
-- WHY THIS FILE IS SAFE TO RUN AGAIN. The panel's entrypoint applies every
-- .sql in its schema directory on EVERY start, not only when the database is
-- first created, so this runs many times over the life of an install.
-- player.shop_item has UNIQUE KEY vnum_unique (shop_vnum, item_vnum, count),
-- so INSERT IGNORE adds the row once and does nothing at all thereafter. It
-- never touches a row that is already there and never touches anything else.
--
-- The game cores read the shop tables once, at boot, so the oil appears on the
-- counter at the next start of the game container rather than immediately.
--
-- TO TAKE IT BACK OUT: turning the Custom Experience off stops this file being
-- staged, but it does not remove a row that is already in the database --
-- deleting rows behind an operator's back is not something a build switch
-- should do. Remove it deliberately instead:
--
--     DELETE FROM player.shop_item
--      WHERE shop_vnum = 3 AND item_vnum = 30177 AND count = 1;

INSERT IGNORE INTO shop_item (shop_vnum, item_vnum, count) VALUES (3, 30177, 1);
